config/routes.rb
Rails.application.routes.draw do

  get 'service_hours/index'

  get 'service_hours/show'

  get 'service_hours/create'

  get 'diesel_readings/index'

  get 'diesel_readings/show'

  get 'diesel_readings/create'

get "linegraph" => "homes#show"

  get 'accounts/index'

  get 'accounts/show'

  get 'accounts/add'

  get 'accounts/edit'

  resources :bill_tables
  resources :guard_infos    
  resources :quotation_details
  resources :sender_details
  resources :gen_avails
  resources :gen_expenses
  resources :gen_details
  resources :third_party_providers
  resources :taxes
  resources :banks
	resources :transactions
	resources :accounts
	resources :email_addresses
  resources :diesel_readings
	resources :service_hours
  get "tax_report" => "tax_report#index"
  post "tax_report" => "tax_report#index"
  post "mail_report" => "tax_report#mailReport"

  get 'transactions/index'
  get 'transactions/show'
  post 'transactions/add'
  post 'transactions/create'
  root 'welcome#index'
  get  "dashboard"        => "client_details#dashboard"
  post "dashboard"	 => "client_details#dashboard"
  get "profitloss" => "gen_expenses#profit_loss"
  post "profitloss" => "gen_expenses#profit_loss"
  get "client/:id"   => "client#index"
  post "client/:id" => "client#index"
  get "partylist" => "gen_expenses#party_list"
  post "partylist" => "gen_expenses#party_list"
  get "party_providers" => "gen_expenses#party_providers"
  post "party_providers" => "gen_expenses#party_providers"
  post "third_party_providers/:id" => "third_party_providers#show"
  get  "client"           => "client_details#index"
  post "client"		        => "client_details#index"
  get  "clientdetails"    => "client_details#new"
  post "clientdetails"    => "client_details#new"
  get  "quotations/:id"   => "client_details#quotations"
	get  "active_generators" => "client_details#active_generators"

  get "closed/client_details/:id" => "quotation_details#contractClose"
  get "opened/client_details/:id" => "quotation_details#contractOpen"
  post "closed/client_details/:id" => "quotation_details#contractClose"
  post "opened/client_details/:id" => "quotation_details#contractOpen"
  get  "sender"           => "sender_details#index"
  post "sender"		        => "sender_details#index"
  get  "senderdetails"    => "sender_details#new"
  post "senderdetails"    => "sender_details#new"
  get  "generators"       => "gen_details#index"
  get  "gendetails"       => "gen_details#new"
  post "gendetails"       => "gen_details#new"
  get  "genexpenses"      => "gen_expenses#index"
  get  "expenses"         => "gen_expenses#new" 
	post "bill"         => "gen_expenses#get_bill" 
	get	 "bill"         => "gen_expenses#get_bill" 
  post "expenses"         => "gen_expenses#new"  
	get "download" => "gen_expenses#download"
	post "download" => "gen_expenses#download"
	get "profit_loss" => "gen_expenses#profit_loss"
	post "profit_loss" => "gen_expenses#profit_loss"
  get  "quotationviewer"  => "quotation_details#index"
  get  "profitloss"     => "quotation_details#profitloss"
  get  "thirdparty"       => "third_party_providers#index"
  get  "providers"        => "third_party_providers#new"
  post "providers"        => "third_party_providers#new"
  get  "welcomemail"      => "client_details#mail"
  get  "sendpdfmail/:id"  => "quotation_details#mail"  
  get  "sendpdfmailfake/:id"  => "fake_quotations#mail"  
  get  "notice"           => "quotation_details#notice"
  get  "notice"           => "fake_quotations#notice"
  get  "availableGenerators"     => "gen_avails#new"
  post "availableGenerators"     => "gen_avails#new"
  get  "/approved/quotation_details/:id" => "quotation_details#approve"
  post "/approved/quotation_details/:id" => "quotation_details#approve"

  devise_for :users
    as :user do
      get 'login'               => 'devise/sessions#new'
      post 'login'              => 'devise/sessions#create'
      get 'logout'              => 'devise/sessions#destroy'
      get 'register'            => 'devise/registrations#new'
      get 'registered'          => 'devise/registrations#show'
      get 'passwordReset'       => 'devise/passwords#new'
      get 'changePassword'      => 'devise/passwords#edit'  
      get 'resendConfirmation'  => 'devise/confirmations#new'    
    end

  mount Mercury::Engine => '/'

  resources :client_details do
    member { post :clientUpdate }
  end

  resources :fake_quotations do
    member { post :mercury_update}
  end

  namespace :mercury do
    resources :images
  end
 
  get "*path" => "quotation_details#notfound"      

end

app/models/bank.rb
class Bank < ActiveRecord::Base
  belongs_to :client_detail
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(new_bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to banks_path }
#        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
#        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to banks_path }
#       format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
#        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: 'Bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:name)
    end
    def new_bank_params
      params.require(:bank).permit(:name)
    end


end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<%= form_for(@bank) do |f| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% @bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Bank Name" %><br>
    <% if @bank.name.blank? %>
      <%= f.text_field :name %>
    <% else %>
		<%= f.text_field :name, :value => @bank.name %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<%= render 'welcome/header' %> <br>
<div class="container">
<section class="quotationSection">
    <div class="quotationForm">
    <h2 class="fillForm">Edit Bank</h2>
    <br>
<%= link_to 'Back', banks_path %>

<%= render 'form' %>

    </div> 
</section>
</div>

app/views/banks/index.html.erb
<%= render 'welcome/header' %> <br><br><br><br><br>

<p id="notice"><%= notice %></p>

<h2 class="table-heading">Listing Banks</h2>
<br>
<div class="container">
	<%= link_to 'Add Bank', new_bank_path() %> </br>
<br>
<br>
<div class="container">
<table id="banks" class="display responsive no-wrap" >
  <thead>
    <tr>
      <th>Bank Name</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @banks.each do |bank| %>
      <tr>
        <td><%= bank.name %></td>
        <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<script>
    $(document).ready(function() {
    $('#banks').dataTable({
      responsive: true
    });
  } );
</script>

app/views/banks/new.html.erb
<h1>New Bank</h1>

<%= render 'form' %>

<%= link_to 'Back', banks_path %>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Taxname:</strong>
  <%= @tax.taxName %>
</p>

<p>
  <strong>Taxpercentage:</strong>
  <%= @tax.taxPercentage %>
</p>

<%= link_to 'Edit', edit_tax_path(@tax) %> |
<%= link_to 'Back', taxes_path %>