config/routes.rb
Rails.application.routes.draw do

  get 'service_hours/index'

  get 'service_hours/show'

  get 'service_hours/create'

  get 'diesel_readings/index'

  get 'diesel_readings/show'

  get 'diesel_readings/create'

get "linegraph" => "homes#show"

  get 'accounts/index'

  get 'accounts/show'

  get 'accounts/add'

  get 'accounts/edit'

  resources :bill_tables
  resources :guard_infos    
  resources :quotation_details
  resources :sender_details
  resources :gen_avails
  resources :gen_expenses
  resources :gen_details
  resources :third_party_providers
  resources :taxes
  resources :banks
	resources :transactions
	resources :accounts
	resources :email_addresses
  resources :diesel_readings
	resources :service_hours
  get "tax_report" => "tax_report#index"
  post "tax_report" => "tax_report#index"
  post "mail_report" => "tax_report#mailReport"

  get 'transactions/index'
  get 'transactions/show'
  post 'transactions/add'
  post 'transactions/create'
  root 'welcome#index'
  get  "dashboard"        => "client_details#dashboard"
  post "dashboard"	 => "client_details#dashboard"
  get "profitloss" => "gen_expenses#profit_loss"
  post "profitloss" => "gen_expenses#profit_loss"
  get "client/:id"   => "client#index"
  post "client/:id" => "client#index"
  get "partylist" => "gen_expenses#party_list"
  post "partylist" => "gen_expenses#party_list"
  get "party_providers" => "gen_expenses#party_providers"
  post "party_providers" => "gen_expenses#party_providers"
  post "third_party_providers/:id" => "third_party_providers#show"
  get  "client"           => "client_details#index"
  post "client"		        => "client_details#index"
  get  "clientdetails"    => "client_details#new"
  post "clientdetails"    => "client_details#new"
  get  "quotations/:id"   => "client_details#quotations"
	get  "active_generators" => "client_details#active_generators"

  get "closed/client_details/:id" => "quotation_details#contractClose"
  get "opened/client_details/:id" => "quotation_details#contractOpen"
  post "closed/client_details/:id" => "quotation_details#contractClose"
  post "opened/client_details/:id" => "quotation_details#contractOpen"
  get  "sender"           => "sender_details#index"
  post "sender"		        => "sender_details#index"
  get  "senderdetails"    => "sender_details#new"
  post "senderdetails"    => "sender_details#new"
  get  "generators"       => "gen_details#index"
  get  "gendetails"       => "gen_details#new"
  post "gendetails"       => "gen_details#new"
  get  "genexpenses"      => "gen_expenses#index"
  get  "expenses"         => "gen_expenses#new" 
	post "bill"         => "gen_expenses#get_bill" 
	get	 "bill"         => "gen_expenses#get_bill" 
  post "expenses"         => "gen_expenses#new"  
	get "download" => "gen_expenses#download"
	post "download" => "gen_expenses#download"
	get "profit_loss" => "gen_expenses#profit_loss"
	post "profit_loss" => "gen_expenses#profit_loss"
  get  "quotationviewer"  => "quotation_details#index"
  get  "profitloss"     => "quotation_details#profitloss"
  get  "thirdparty"       => "third_party_providers#index"
  get  "providers"        => "third_party_providers#new"
  post "providers"        => "third_party_providers#new"
  get  "welcomemail"      => "client_details#mail"
  get  "sendpdfmail/:id"  => "quotation_details#mail"  
  get  "sendpdfmailfake/:id"  => "fake_quotations#mail"  
  get  "notice"           => "quotation_details#notice"
  get  "notice"           => "fake_quotations#notice"
  get  "availableGenerators"     => "gen_avails#new"
  post "availableGenerators"     => "gen_avails#new"
  get  "/approved/quotation_details/:id" => "quotation_details#approve"
  post "/approved/quotation_details/:id" => "quotation_details#approve"

  devise_for :users
    as :user do
      get 'login'               => 'devise/sessions#new'
      post 'login'              => 'devise/sessions#create'
      get 'logout'              => 'devise/sessions#destroy'
      get 'register'            => 'devise/registrations#new'
      get 'registered'          => 'devise/registrations#show'
      get 'passwordReset'       => 'devise/passwords#new'
      get 'changePassword'      => 'devise/passwords#edit'  
      get 'resendConfirmation'  => 'devise/confirmations#new'    
    end

  mount Mercury::Engine => '/'

  resources :client_details do
    member { post :clientUpdate }
  end

  resources :fake_quotations do
    member { post :mercury_update}
  end

  namespace :mercury do
    resources :images
  end
 
  get "*path" => "quotation_details#notfound"      

end

app/controllers/tax_report_controller.rb
class TaxReportController < ApplicationController
	before_action :authenticate_user! 

  def index
    if not params[:start_date].blank?
      start_d =  Date::civil(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i)
      end_d = Date::civil(params[:end_date][:year].to_i, params[:end_date][:month].to_i, params[:end_date][:day].to_i)

      start_d = start_d.beginning_of_day
      end_d = end_d.end_of_day
    end
    if not params[:start_date].blank?
      @bill = BillTable.where(created_at: (start_d)..end_d)
    else
      @bill = BillTable.all
    end
    respond_to do |format|
      format.html
      format.csv {render text: @bill.to_csv}
    end
  end
	def mailReport
		filename = "Full Report"
    if not params[:start_date].blank?
      start_d =  Date::civil(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i)
      end_d = Date::civil(params[:end_date][:year].to_i, params[:end_date][:month].to_i, params[:end_date][:day].to_i)

      start_d = start_d.beginning_of_day
      end_d = end_d.end_of_day
		 filename = start_d.to_formatted_s(:long_ordinal) + " TO " + end_d.to_formatted_s(:long_ordinal)
    end
    if not params[:start_date].blank?
      @bill = BillTable.where(created_at: (start_d)..end_d)
    else
      @bill = BillTable.all
    end
		 to = EmailAddresse.find_by(name: "accountant")
		 from = EmailAddresse.find_by(name: "my")
		 filename = filename + ".csv"
		 QtMailer.tax_report_email(to.address , from.address, "Tax Reports: " + filename, @bill.to_csv, filename).deliver
     respond_to do |format|
            format.json { head :no_content }
		 end
	end



end

app/views/tax_report/index.html.erb
<%= render 'welcome/header' %> 
<div class="container">

<section class="quotation_Section">
<div class="quotation_Form">
<h2 class="table-heading">Service Tax / Surcharge / Tds</h2>

        <div style="margin-left:10%;">
      	<%= form_for :Date do |f| %>
		<% if not params[:start_date].blank?
			start_d =  Date::civil(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i) 
			end_d = Date::civil(params[:end_date][:year].to_i, params[:end_date][:month].to_i, params[:end_date][:day].to_i) %>
			From <%= select_date start_d, prefix: :start_date %> 
			To <%= select_date end_d, prefix: :end_date %>
		<% else %>
			From <%= select_date Date.today, prefix: :start_date %> 
			To <%= select_date Date.today, prefix: :end_date %>
		<% end %>

<span class="actions">
		<%= f.submit value:"Filter Result", :class=> 'form_submit' %>
	<span>
        </div>
		<% end %>
<%

        if not params[:start_date].blank?
                start_d =  Date::civil(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i)
                end_d = Date::civil(params[:end_date][:year].to_i, params[:end_date][:month].to_i, params[:end_date][:day].to_i)

                start_d = start_d.beginning_of_day
                end_d = end_d.end_of_day
end
%>

<%
				if not params[:start_date].blank?
                	@bill = @bill.where(created_at: (start_d)..end_d)
                end
			%>
				<%= line_chart [
					{name: "Service Tax", data: @bill.map{|record| [record.created_at, record.calc_stax]}},
					{name: "Surcharge", data: @bill.map{|record| [record.created_at, record.calc_surcharge]}},
					{name: "TDS", data: @bill.map{|record| [record.created_at, record.calc_tds ]}}
				], { library:{width: 1200} } %>
			<%
					dates = Hash.new
			if not params[:start_date].blank?
					dates["start_date[month]"] = params[:start_date][:month]
					dates["start_date[year]"] = params[:start_date][:year]
					dates["start_date[day]"] = params[:start_date][:day]
					dates["end_date[month]"] = params[:end_date][:month]
					dates["end_date[year]"] = params[:end_date][:year]
					dates["end_date[day]"] = params[:end_date][:day]
			end
						%>
					<p style="float:right">
						<%= button_to "Email Accountant", mail_report_path(format: "json"), params: dates, id: "emailAccountant", class: "send pull-right", remote: true, data: { disable_with: "Please wait.." } %> 
						<%= button_to "Download CSV", tax_report_path(format: "csv"), params: dates, class: "send pull-right" %>
<script>
	$(document).ready(function(){
		$('.button_to').on('ajax:success',function(e, data, status, xhr){
			alert("Email Sent to accountant for the selected range.");
    });
  });
</script>

					</p>
<table id="service_tax" class="display responsive no-wrap">

	<thead>
		<tr>
			<th></th>
			<th>Bill Number</th>
			<th>Service Tax</th>
			<th>Surcharge</th>
			<th>TDS</th>
		</tr>
	</thead>   
	<tbody>
  	<% 
	i = 0
	@bill.each do |b| 
	i= i+1
  	%>   
		<tr>
			<td><%= i %></td>
			<td><%= b.bill_no %></td>
			<td><%= b.calc_stax %></td>
			<td><%= b.calc_surcharge %></td>
			<td><%= b.calc_tds %></td>

		</tr>
  	<% end %>  
  	</tbody>

</table>
</div>


<script>
	$(document).ready(function() {
		$('#service_tax').dataTable({
			responsive: true
		});
	} );
</script>

<script>
	$(document).ready(function() {
		$('#tds').dataTable({
			responsive: true
		});
	} );
</script>
</section>
</div>

app/views/tax_report/indexx.html.erb
<%= render 'welcome/header' %> <br><br><br><br><br>

<div class="container">
	<h2 class="table-heading">Search Quotations</h2>

	<div style="margin-left:18%;">
	<%= form_for :Date do |f| %>
		From <%= select_date Date.today, prefix: :start_date %>
 
To		<%= select_date Date.today, prefix: :end_date %></p></br>
	<p> 
	</div>
	<div style="margin-left:23%;">
		Bank Name <%= f.collection_select :bank_id, Bank.all, :id, :name, prompt: true, autofocus: true, :class => 'dropDown new-dropdown'  %> &nbsp;
		&nbsp;	Bank Branch Name &nbsp; <%= f.text_field :bank_branch, autofocus: true,  :placeholder => 'Bank Branch Name',:title => 'Bank Branch Name' %>
</div><br> <br>
<div class="actions">
<%= f.submit value:"Filter Result", :class=> 'form_submit' %>
</div>

	</p>
<% end %>


<%#= render :text => params[:start_date][:year].inspect %>
<%#= render :text => params[:end_date].inspect %>
<%

	if not params[:start_date].blank?
		start_d =  Date::civil(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i) 
		end_d = Date::civil(params[:end_date][:year].to_i, params[:end_date][:month].to_i, params[:end_date][:day].to_i)

		start_d = start_d.beginning_of_day
		end_d = end_d.end_of_day
end
%>
</div> <br> <hr> <br>
	<h2 class="table-heading">Real Quotations</h2>
<table id="realQuotations" class="display responsive no-wrap">

	<thead>
		<tr>
			<th></th>
			<th>Sender Name</th>
			<th>Bank Name</th>
			<th>District</th>      
			<th>Contact Number</th>
			<th>Email ID</th>
			<th>Show Quotations</th>
			<th>Edit Client</th>
			<th>Approve</th>    
			<th>Contract</th> 
		</tr>
	</thead>   
  <tbody>
  <% 
i = 0
j = 0
@sender_details.each do |s| 
	if s.quotationType == "Real" 
		@client_details = ClientDetail.where(sender_details_id: s.id)
		if not params[:Date].blank?
			if not params[:start_date].blank? 
				@client_details = @client_details.where(created_at: (start_d)..end_d)
			end
			if not params[:Date][:bank_branch].blank?
			end
			@client_details = @client_details.where('bank_branch LIKE ?', '%' + params[:Date][:bank_branch].to_s + '%')
			if not params[:Date][:bank_id].blank?
				@client_details = @client_details.where(bank_id: params[:Date][:bank_id])
			end
		end
		@client_details = @client_details.order(id: :desc) 
		@client_details.each do |f| 
			i= i+1
		%>   
	<tr>
		<td><%= i %></td>
		<td><%= s.name %></td>
		<td>
			<%	bank=""
			if not f.bank_id.blank? 
				bank= Bank.find(f.bank_id).name 
			end	%>
		<%= bank.html_safe %>, 
		<%= f.bank_branch.html_safe  %>
	</td>
	<td><%= f.district %></td>      
	<td><%= f.contactNo %></td>
	<td><%= f.emailID %></td> 
	<td><%= link_to "Show", "/quotations/" + f.id.to_s %></td> 
	<td><%= link_to "Edit", client_detail_path(f.id) + "/edit" %></td>
	<% if f.approved == true %> 
		<td>Approved</td>
	<% else %>
		<td><%= button_to 'Approve', "/approved" + quotation_detail_path(f.id) %></td> 
	<% end %>      
	<% if f.contract == true %>
		<td><%= button_to  'Close', "/closed" + client_detail_path(f.id) %></td>  
	<% else %>
		<td> Contract Closed </td>
	<% end %>
</tr>
	  <% end %>
  <% end %>
  <% end %>  
  </tbody>

</table>
<h2 class="table-heading">Fake Quotations</h2>


<table id="fakeQuotations" class="display responsive no-wrap">

	<thead>
		<tr>
			<th></th>
			<th>Sender Name</th>
			<th>Bank Name</th>
			<th>District</th>      
			<th>Contact Number</th>
			<th>Email ID</th>
			<th>Show Quotations</th>
			<th>Edit Client</th>
		</tr>
	</thead>  

	<tbody>
		<% 
				@sender_details.each do |s| %>
			<% if s.quotationType == "Fake" %>
				<% @client_details = ClientDetail.where(sender_details_id: s.id)  %>
				<%
					if not params[:Date].blank?
			if not params[:start_date].blank? 
				@client_details = @client_details.where(created_at: (start_d)..end_d)
			end
			if not params[:Date][:bank_branch].blank?
			end
			@client_details = @client_details.where('bank_branch LIKE ?', '%' + params[:Date][:bank_branch].to_s + '%')
			if not params[:Date][:bank_id].blank?
				@client_details = @client_details.where(bank_id: params[:Date][:bank_id])
			end
		end
		@client_details = @client_details.order(id: :desc) 
	
				 @client_details.each do |f| %>    
				<% 
						@fake_qtn = FakeQuotation.where(client_details_id: f.id).order(id: :desc)
				qtn_id = ''
				@fake_qtn.each do |q|
					qtn_id = q.id
				end
				j = 1+j
			%>
		<tr>
			<td><%= j %></td>
			<td><%= s.name%></td>          


			<td>
				<%	bank=""
				if not f.bank_id.blank? 
					bank= Bank.find(f.bank_id).name 
				end	%>
			<%= bank.html_safe %>, 
			<%= f.bank_branch.html_safe  %> 
		</td>
		<td><%= f.district %></td>      
		<td><%= f.contactNo %></td>
		<td><%= f.emailID %></td> 
		<td><%= link_to "Show", "/fake_quotations/" + qtn_id.to_s %></td>
		<td><%= link_to "Edit", client_detail_path(f.id) + "/edit" %></td>
	<% end %>  
</tr>
	<% end %>  
<% end %>
  </tbody>

</table>
</div>


<script>
	$(document).ready(function() {
		$('#realQuotations').dataTable({
			responsive: true
		});
	} );
</script>

<script>
	$(document).ready(function() {
		$('#fakeQuotations').dataTable({
			responsive: true
		});
	} );
</script>

app/views/tax_report/new.html.erb
<h1>create page</h1>